Repository cvnoort/motivation-webapp, pull requests merged in 2025-01, with the labels that each got.

#9 Upload favicon
  index.html
  public/images/favicon.ico
Labels: enhancement

#6 Add gh-pages badge to README
  README.md
Labels: documentation

#8 Add dynamic Open Graph meta tags
  index.html
  package-lock.json
  package.json
  src/Sharing.jsx
  src/TextQuotes.jsx
Labels: enhancement

#7 Move images folder
  public/images/background-1
  public/images/background-1.jpg
  public/images/background-10
  public/images/background-10.jpg
  public/images/background-11
  public/images/background-11.jpg
  public/images/background-12
  public/images/background-12.jpg
  public/images/background-13
  public/images/background-13.jpg
  public/images/background-14
  public/images/background-14.jpg
  public/images/background-15
  public/images/background-15.jpg
  public/images/background-2
  public/images/background-2.jpg
  public/images/background-3
  public/images/background-3.jpg
  public/images/background-4
  public/images/background-4.jpg
  public/images/background-5
  public/images/background-5.jpg
  public/images/background-6
  public/images/background-6.jpg
  public/images/background-7
  public/images/background-7.jpg
  public/images/background-8
  public/images/background-8.jpg
  public/images/background-9
  public/images/background-9.jpg
  src/BackgroundImgs.jsx
Labels: bug

#11 Update image path
  src/BackgroundImgs.jsx
Labels: bug

#12 Reduce text size and increase bg on small screens
  src/App.css
  src/index.css
Labels: enhancement

#4 Code Citation / Button Description
  index.html
  src/App.css
  src/App.jsx
  src/BackgroundImgs.jsx
  src/index.css
Labels: enhancement

#14 Fix CSS typo
  src/index.css
Labels: bug
